services:
  - type: web
    name: shatin-vps-deploy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 你的 Bot Token（例如 7386xxxx:AA...）
      - key: TELEGRAM_USER_ID
        value: 214241911
      - key: WEBHOOK_URL
        value: https://你的-render-url.onrender.com