services:
  - type: worker
    name: shatin-vps-deploy
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python3 src/main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7386971571:AAExoA9q7RhREOzR_edIbBLAyhRRZg-9BsA
