services:
  - type: web
    name: shatin-vps-deploy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7386971571:AAExoA9q7RhREOzR_edIbBLAyhRRZg-9BsA
      - key: TELEGRAM_USER_ID
        value: 214241911
      - key: WEBHOOK_URL
        value: https://shatin-vps-deploy.onrender.com