
services:
  - type: worker
    name: shatin-racing-bot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here
      - key: TELEGRAM_CHAT_ID
        value: 214241911
