services:
  - type: web
    name: shatin-racebot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
